// This included files are generated by the ASIC group for
// baseband platforms.

// 2045X0 reg map
#ifdef BB_2045X0
    #include "2045mapx0.h"


// 2045B0 reg map
#elif ( defined(BB_2045B2) || defined(BB_2045B3) )
    #include "2045mapb2.h"
#elif BB_2045B1
    #include "2045mapb1.h"
#elif BB_2045B0
    #include "2045mapb0.h"

#elif defined(BB_2046B1)
    #include "2046mapb1.h"
#elif defined(BB_2046B0)
    #include "2046mapb0.h"
#elif (defined(BB_2046A0))
    #include "2046mapa0.h"

#elif defined(BT_FW_AUDIO_CORE)
    #if defined(BB_20748A0)
        #include "20748mapa0.h"
    #elif defined(BB_2074A0)
        #include "2074mapa0.h"
    #elif defined(BB_2047A0)
        #include "2047mapa0.h"
    #elif defined(BB_2044B0)
        #include "2044mapb0.h"
    #elif defined(BB_2044A0)
        #include "2044mapa0.h"
    #endif

#elif defined(BB_20730B0)
    #include "20730mapb0.h"
#elif defined(BB_20730A1)
    #include "20730mapa1.h"
#elif defined(BB_20730A0)
    #include "20730mapa0.h"

#elif defined (BB_20732A0)
    #include "20732mapa0.h"
#elif defined (BB_20732A1)
    #include "20732mapa1.h"
#elif defined(BB_20733A2)
    #include "20733mapa2.h"    
#elif defined(BB_20733A1)
    #include "20733mapa1.h"
#elif defined(BB_20733A0)
    #include "20733mapa0.h"   

#elif defined(BB_2072)
    #include "2072map.h"
// For 20702, we need to use the 2070 BB compile flags for other parts of the code. 
// For the map inclusion, check for 20702 compile flag first so that we don't use the 2070 map
#elif defined(BB_20702B0)
    #include "20702mapb0.h"
// 20702a0 and 20702a1 chips both use the 20702mapa0.h file
#elif defined(BB_20702A1)
    #include "20702mapa0.h"
#elif defined(BB_20702A0)
    #include "20702mapa0.h"
#elif defined(BB_2070B0)
    #include "2070mapb0.h"
#elif defined(BB_2070A0)
    #include "2070mapa0.h"

#elif defined(BB_20703A0)
    #include "20703mapa0.h"
    #include "compatible.h"

#elif defined(BB_2049C0)
    #include "2049mapc0.h"    
#elif defined(BB_2049B0)
    #include "2049mapb0.h"
#elif defined(BB_2049A0)
    #include "2049mapa0.h"

#elif defined(BB_2075C0)
    #include "2075mapc0.h"
#elif defined(BB_2075B0)
    #include "2075mapb0.h"
#elif defined(BB_2075A0)
    #include "2075mapa0.h"
#elif ( defined(BB_2076B0) || defined(BB_2076B1) )
    #include "2076mapb0.h"
    #include "2076_iomux.h"
#elif ( defined(BB_2076A0) || defined(BB_2076A2) )
    #include "2076mapa0.h"
    #include "2076_iomux.h"
#elif defined(BB_43242A1)	
    #include "43242mapa0.h"
#elif defined(BB_43242A0)	
    #include "43242mapa0.h"
#elif defined(BB_4324B0)	
	#include "4324mapb0.h"    
#elif defined(BB_4324B1)	
	#include "4324mapb1.h"    
#elif defined(BB_43241B0)	
	#include "4324mapb0.h"    
#elif defined(BB_4324A0)	
	#include "4324mapa0.h"
#elif defined(BB_4337A0)	
	#include "4337mapa0.h"
#elif (defined(BB_4335A0) || defined(BB_4335C0))
  #include "4335mapa0.h"
#elif defined(BB_43341A0)
    #include "43341mapa0.h"
#elif defined(BB_43342A0)	
	#include "43342mapa0.h"
#elif defined(BB_4334B0)
    #include "4334mapb0.h"
#elif defined(BB_4334A0)	
	#include "4334mapa0.h"
#elif defined(BB_4330C0)
	#include "4330mapc0.h"
#elif defined(BB_4330B1)
	#include "4330mapb1.h"
#elif defined(BB_4330B0)
	#include "4330mapb0.h"
#elif ( defined(BB_4330A0) || defined(BB_4330A1) )
	#include "4330mapa1.h"

#elif defined(BB_4314A0)
	#include "4314mapa0.h"

#elif defined(BB_4329B0)
	#include "4329mapb0.h"
#elif defined(BB_4329A0)
	#include "4329mapa0.h"
#elif defined(BB_4325A0)
	#include "4325mapa0.h"


#elif defined(BB_2048K0)    // Test Chip
	#include "2048mapa1.h"
#elif defined(BB_2048B0)
    #include "2048mapa1.h"
#elif defined(BB_2048A2)
    #include "2048mapa1.h"
#elif defined(BB_2048A1) 
	#include "2048mapa1.h"
#elif defined(BB_2048A0)
    #include "2048mapa0.h"

#elif defined(BB_20785A0)
	#include "20785mapa0.h"
#elif defined(BB_4350A0)
  #include "4350mapa0.h"
#elif defined(BB_4350C0)
  #include "4350mapc0.h"
#elif defined(BB_4349A0)
  #include "4349mapa0.h"
  #include "compatible.h"
#elif defined(BB_4345TC)
  #include "4345mapa0.h"
  #include "compatible.h"
#elif defined (BB_43457A0)
  #include "43457mapa0.h"
  #include "compatible.h"
#elif defined(BB_4345B0)
  #include "4345mapb0.h"
  #include "compatible.h"
#elif defined(BB_4345A0)
  #include "4345mapa0.h"
  #include "compatible.h"
#else
 #error ASIC flag not defined...(BB_xxxxx)
#endif

