/*
 * This file has been automatically generated by the WICED Smart Designer. 
 * BLE device's GATT database, device configuration, function that can be used
 * to send notifications and indications.
 *
 */
