/*
 * This file has been automatically generated by the WICED Smart Designer.
 * BLE device's GATT database, device configuration, function that can be used
 * to send notifications and indications.
 *
 */

// location_and_navigation_db.c

#include "bleprofile.h"
#include "bleapp.h"
#include "gpiodriver.h"
#include "string.h"
#include "stdio.h"
#include "platform.h"
#include "location_and_navigation_db.h"

const UINT8 gatt_database[]= // Define GATT database
{
// ***** Primary service 'Generic Access'
    //<Name>Generic Access</Name>
    //<Uuid>1800</Uuid>
    //Service handle: HDLS_GENERIC_ACCESS
    //Service UUID: UUID_SERVICE_GAP
    PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ACCESS, UUID_SERVICE_GAP),

    //<Name>Device Name</Name>
    //<Uuid>2A00</Uuid>
    CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_DEVICE_NAME,
                           HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE,
                           UUID_CHARACTERISTIC_DEVICE_NAME,
                           LEGATTDB_CHAR_PROP_READ,
                           LEGATTDB_PERM_READABLE,
                           16),
    'B','L','E',' ','L','N',0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,

    //<Name>Appearance</Name>
    //<Uuid>2A01</Uuid>
    CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_APPEARANCE,
                           HDLC_GENERIC_ACCESS_APPEARANCE_VALUE,
                           UUID_CHARACTERISTIC_APPEARANCE,
                           LEGATTDB_CHAR_PROP_READ,
                           LEGATTDB_PERM_READABLE,
                           2),
    BIT16_TO_8(APPEARANCE_LOCATION_AND_NAVIGATION_POD),

// ***** Primary service 'Generic Attribute'
    //<Name>Generic Attribute</Name>
    //<Uuid>1801</Uuid>
    //Service handle: HDLS_GENERIC_ATTRIBUTE
    //Service UUID: UUID_SERVICE_GATT
    PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ATTRIBUTE, UUID_SERVICE_GATT),

// ***** Primary service 'Location and Navigation'
    //<Name>Location and Navigation</Name>
    //<Uuid>1819</Uuid>
    //Service handle: HDLS_LOCATION_AND_NAVIGATION
    //Service UUID: __UUID_LOCATION_AND_NAVIGATION
    PRIMARY_SERVICE_UUID16 (HDLS_LOCATION_AND_NAVIGATION, __UUID_LOCATION_AND_NAVIGATION),

    //<Name>LN Feature</Name>
    //<Uuid>2A6A</Uuid>
    CHARACTERISTIC_UUID16 (HDLC_LOCATION_AND_NAVIGATION_LN_FEATURE,
                           HDLC_LOCATION_AND_NAVIGATION_LN_FEATURE_VALUE,
                           __UUID_LOCATION_AND_NAVIGATION_LN_FEATURE,
                           LEGATTDB_CHAR_PROP_READ,
                           LEGATTDB_PERM_READABLE,
                           4),
    0x83,0x0d,0x02,0x00, //Instantaneous Speed Supported,
                         //Total Distance Supported,
                         //Remaining Distance Supported,
                         //Remaining Vertical Distance Supported,
                         //Number of Beacons in Solution Supported,
                         //Number of Beacons in View Supported,
                         //Location and Speed Characteristic Content Masking Supported,

    //<Name>Location and Speed</Name>
    //<Uuid>2A67</Uuid>
    CHARACTERISTIC_UUID16 (HDLC_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED,
                           HDLC_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED_VALUE,
                           __UUID_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED,
                           LEGATTDB_CHAR_PROP_NOTIFY,
                           LEGATTDB_PERM_NONE,
                           20),
    0x03,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,

    //<ClientConfiguration>
    //<Notification>false</Notification>
    //<Indication>false</Indication>
    CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED_CLIENT_CONFIGURATION,
                                     UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                                     //LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_RELIABLE_WRITE | LEGATTDB_PERM_AUTH_WRITABLE,
                                     LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ,
                                     2),
    BIT16_TO_8 (CCC_NONE),

    //<Name>Position Quality</Name>
    //<Uuid>2A69</Uuid>
    CHARACTERISTIC_UUID16 (HDLC_LOCATION_AND_NAVIGATION_POSITION_QUALITY,
                           HDLC_LOCATION_AND_NAVIGATION_POSITION_QUALITY_VALUE,
                           __UUID_LOCATION_AND_NAVIGATION_POSITION_QUALITY,
                           LEGATTDB_CHAR_PROP_READ,
                           LEGATTDB_PERM_READABLE,
                           4),
    0x03,0x00,0x00,0x00, //Number of Beacons in Solution Present,
                         //Number of Beacons in View Present,

    //<Name>LN Control Point</Name>
    //<Uuid>2A6B</Uuid>
    CHARACTERISTIC_UUID16_WRITABLE (HDLC_LOCATION_AND_NAVIGATION_LN_CONTROL_POINT,
                           HDLC_LOCATION_AND_NAVIGATION_LN_CONTROL_POINT_VALUE,
                           __UUID_LOCATION_AND_NAVIGATION_LN_CONTROL_POINT,
                           LEGATTDB_CHAR_PROP_INDICATE | LEGATTDB_CHAR_PROP_WRITE,
                           LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_VARIABLE_LENGTH,
                           19),
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,

    //<ClientConfiguration>
    //<Notification>false</Notification>
    //<Indication>false</Indication>
    CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_LOCATION_AND_NAVIGATION_LN_CONTROL_POINT_CLIENT_CONFIGURATION,
                                     UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                                     //LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_RELIABLE_WRITE | LEGATTDB_PERM_AUTH_WRITABLE,
                                     LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ,
                                     2),
    BIT16_TO_8 (CCC_NONE),

    //<Name>Navigation</Name>
    //<Uuid>2A68</Uuid>
    CHARACTERISTIC_UUID16 (HDLC_LOCATION_AND_NAVIGATION_NAVIGATION,
                           HDLC_LOCATION_AND_NAVIGATION_NAVIGATION_VALUE,
                           __UUID_LOCATION_AND_NAVIGATION_NAVIGATION,
                           LEGATTDB_CHAR_PROP_NOTIFY,
                           LEGATTDB_PERM_NONE,
                           12),
    0x03,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,

    //<ClientConfiguration>
    //<Notification>false</Notification>
    //<Indication>false</Indication>
    CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_LOCATION_AND_NAVIGATION_NAVIGATION_CLIENT_CONFIGURATION,
                                     UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                                     //LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_RELIABLE_WRITE | LEGATTDB_PERM_AUTH_WRITABLE,
                                     LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ,
                                     2),
    BIT16_TO_8 (CCC_NONE),

};
// Indication sent, waiting for ack
UINT8 location_and_navigation_indication_sent = 0;
// Length of the GATT database
const UINT16 gatt_database_len = sizeof(gatt_database);
// Pointer to the bonded peer info or NULL if not bonded
__HOSTINFO *p_bonded = NULL;
// Following structure defines GPIO configuration used by the application
const BLE_PROFILE_GPIO_CFG location_and_navigation_gpio_cfg =
{
    {
        GPIO_PIN_WP,                               // This need to be used to enable/disable NVRAM write protect
        -1, -1, -1, -1, 
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 // Other GPIOs are not used
    },
    /*.gpio_flag =*/
    {
        GPIO_SETTINGS_WP,
        0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    }
};

// Main vendor specific service. 1 byte length means no such service
UINT8 location_and_navigation_uuid_main_vsc_service[1] = {0};
// Timer counter (for the trace)
UINT32 __timer_count = 0;
// Indication confirmation callback
void __indication_cfm()
{
    location_and_navigation_indication_sent = 0;
    location_and_navigation_indication_cfm();
}

// Timer callback function for location_and_navigation_reg_timer
void location_and_navigation_timeout(UINT32 arg)
{
    ble_trace1("timeout:%d\n", __timer_count++);
    if (arg == BLEPROFILE_GENERIC_APP_TIMER)
    {
        location_and_navigation_timer_1s();
    }
}
// Timer callback function for location_and_navigation_reg_timer
void location_and_navigation_fine_timeout(UINT32 arg)
{
    location_and_navigation_timer_fine();
}

// Registers timer. Should be called from location_and_navigation_create()
void location_and_navigation_reg_timer()
{
    bleprofile_regTimerCb(location_and_navigation_fine_timeout, location_and_navigation_timeout);
    bleprofile_StartTimer();
}

// Finds bonded peer in the hostinfo. On exit p_bonded points on bonded peer or NULL
__HOSTINFO *__find_bonded_peer(UINT8 *bda)
{
    p_bonded = NULL;
    if (0 == memcmp(bda, p_hostinfo_generated->bdaddr, 6))
    {
        p_bonded = p_hostinfo_generated;
    }
    return p_bonded;
}

// initializes persistent values in the hostinfo to add bonded peer
void location_and_navigation_add_bond(UINT8 *bda)
{
    // Find this peer among bonded peers in the p_hostinfo_generated
    if (!__find_bonded_peer(bda));
    {
        // Peer is not found. Remember new one.
        p_bonded = p_hostinfo_generated;
        memcpy(p_bonded->bdaddr, bda, 6);
    }

    // Clear persistent generated values in the hostinfo for just bonded peer

    // Set the initial value of the client configuration descriptor for value 'Location and Speed'
    p_bonded->location_and_navigation_location_and_speed_client_configuration = 0;

    // Set the initial value of the client configuration descriptor for value 'LN Control Point'
    p_bonded->location_and_navigation_ln_control_point_client_configuration = 0;

    // Set the initial value of the client configuration descriptor for value 'Navigation'
    p_bonded->location_and_navigation_navigation_client_configuration = 0;
}

// Prepares generated code for connection - writes persistent values from __HOSTINFO to GATT DB
void __on_connection_up()
{
    location_and_navigation_indication_sent = 0;
    // Find this peer among bonded peers in the p_hostinfo_generated
    if (__find_bonded_peer(location_and_navigation_remote_addr))
    {
        BLEPROFILE_DB_PDU db_pdu;

        // Write the value of the client configuration descriptor for value 'Location and Speed'
        db_pdu.len = 2;
        db_pdu.pdu[0] = p_bonded->location_and_navigation_location_and_speed_client_configuration & 0xff;
        db_pdu.pdu[1] = (p_bonded->location_and_navigation_location_and_speed_client_configuration >> 8) & 0xff;
        //bleprofile_WriteHandle(HDLD_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED_CLIENT_CONFIGURATION, &db_pdu);

        // Write the value of the client configuration descriptor for value 'LN Control Point'
        db_pdu.len = 2;
        db_pdu.pdu[0] = p_bonded->location_and_navigation_ln_control_point_client_configuration & 0xff;
        db_pdu.pdu[1] = (p_bonded->location_and_navigation_ln_control_point_client_configuration >> 8) & 0xff;
        //bleprofile_WriteHandle(HDLD_LOCATION_AND_NAVIGATION_LN_CONTROL_POINT_CLIENT_CONFIGURATION, &db_pdu);

        // Write the value of the client configuration descriptor for value 'Navigation'
        db_pdu.len = 2;
        db_pdu.pdu[0] = p_bonded->location_and_navigation_navigation_client_configuration & 0xff;
        db_pdu.pdu[1] = (p_bonded->location_and_navigation_navigation_client_configuration >> 8) & 0xff;
        //bleprofile_WriteHandle(HDLD_LOCATION_AND_NAVIGATION_NAVIGATION_CLIENT_CONFIGURATION, &db_pdu);
    }
}

// Updates __HOSTINFO by the value written by peer.
// Returns true if any persistent value is changed
int __write_handler(UINT16 handle, int len, UINT8 *attrPtr, BOOL *changed)
{
    int ret = 0;
    if ((len == 2) && (handle == HDLD_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED_CLIENT_CONFIGURATION))
    {
        // find this peer among bonded peers in the p_hostinfo_generated
        if (__find_bonded_peer(location_and_navigation_remote_addr))
        {
            p_bonded->location_and_navigation_location_and_speed_client_configuration = attrPtr[0] + (attrPtr[1] << 8);
            ble_trace2("handle:%02x val:%04x", handle, p_bonded->location_and_navigation_location_and_speed_client_configuration);
            *changed = TRUE;
        }
    }
    if ((len == 2) && (handle == HDLD_LOCATION_AND_NAVIGATION_LN_CONTROL_POINT_CLIENT_CONFIGURATION))
    {
        // find this peer among bonded peers in the p_hostinfo_generated
        if (__find_bonded_peer(location_and_navigation_remote_addr))
        {
            p_bonded->location_and_navigation_ln_control_point_client_configuration = attrPtr[0] + (attrPtr[1] << 8);
            ble_trace2("handle:%02x val:%04x", handle, p_bonded->location_and_navigation_ln_control_point_client_configuration);
            *changed = TRUE;
        }
    }
    if ((len == 2) && (handle == HDLD_LOCATION_AND_NAVIGATION_NAVIGATION_CLIENT_CONFIGURATION))
    {
        // find this peer among bonded peers in the p_hostinfo_generated
        if (__find_bonded_peer(location_and_navigation_remote_addr))
        {
            p_bonded->location_and_navigation_navigation_client_configuration = attrPtr[0] + (attrPtr[1] << 8);
            ble_trace2("handle:%02x val:%04x", handle, p_bonded->location_and_navigation_navigation_client_configuration);
            *changed = TRUE;
        }
    }
    if (handle == HDLC_LOCATION_AND_NAVIGATION_LN_CONTROL_POINT_VALUE)
    {
        if (len > 19)
        {
            ble_trace2("bad length:%d handle:%04x", len, handle);
        }
        else
        {
            //call custom on_write function
            ble_trace1("write handle:%04x", handle);
            ret = on_write_location_and_navigation_ln_control_point(len, attrPtr, changed);
        }
    }
    return ret;
}

// It should be called when 'Device Name' is changed.
BOOL store_in_db_generic_access_device_name(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'Appearance' is changed.
BOOL store_in_db_generic_access_appearance(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_GENERIC_ACCESS_APPEARANCE_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_GENERIC_ACCESS_APPEARANCE_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'LN Feature' is changed.
BOOL store_in_db_location_and_navigation_ln_feature(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_LOCATION_AND_NAVIGATION_LN_FEATURE_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_LOCATION_AND_NAVIGATION_LN_FEATURE_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'Location and Speed' is changed.
BOOL store_in_db_location_and_navigation_location_and_speed(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    if (__find_bonded_peer(location_and_navigation_remote_addr))
    {
        // Exit if notify and indicate are not configured in the Client Configuration Descriptor
        if (0 == (p_bonded->location_and_navigation_location_and_speed_client_configuration & (CCC_NOTIFICATION)))
        {
            ble_trace1("don't notify handle:%02x", HDLC_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED_VALUE);
            return TRUE;
        }
        // Just return FALSE if connection is down
        if (location_and_navigation_connection_handle == 0)
        {
            ble_trace1("not connected handle:%02x", HDLC_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED_VALUE);
            return FALSE;
        }
        // Just return FALSE if we are waiting for confirmation
        if (location_and_navigation_indication_sent != 0)
        {
            ble_trace1("wait confirmation handle:%02x", HDLC_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED_VALUE);
            return FALSE;
        }
        // Read the value of the characteristic
        bleprofile_ReadHandle(HDLC_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED_VALUE, &db_pdu);
        // Notify property is true. If client has registered for notification
        if (p_bonded->location_and_navigation_location_and_speed_client_configuration & CCC_NOTIFICATION)
        {
            ble_trace2("notify len:%d handle:%02x", db_pdu.len, HDLC_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED_VALUE);
            bleprofile_sendNotification(HDLC_LOCATION_AND_NAVIGATION_LOCATION_AND_SPEED_VALUE, (UINT8 *)db_pdu.pdu, db_pdu.len);
        }
    }
    return TRUE;
}

// It should be called when 'Position Quality' is changed.
BOOL store_in_db_location_and_navigation_position_quality(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_LOCATION_AND_NAVIGATION_POSITION_QUALITY_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_LOCATION_AND_NAVIGATION_POSITION_QUALITY_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'LN Control Point' is changed.
BOOL store_in_db_location_and_navigation_ln_control_point(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_LOCATION_AND_NAVIGATION_LN_CONTROL_POINT_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_LOCATION_AND_NAVIGATION_LN_CONTROL_POINT_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'Navigation' is changed.
BOOL store_in_db_location_and_navigation_navigation(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    if (__find_bonded_peer(location_and_navigation_remote_addr))
    {
        // Exit if notify and indicate are not configured in the Client Configuration Descriptor
        if (0 == (p_bonded->location_and_navigation_navigation_client_configuration & (CCC_NOTIFICATION)))
        {
            ble_trace1("don't notify handle:%02x", HDLC_LOCATION_AND_NAVIGATION_NAVIGATION_VALUE);
            return TRUE;
        }
        // Just return FALSE if connection is down
        if (location_and_navigation_connection_handle == 0)
        {
            ble_trace1("not connected handle:%02x", HDLC_LOCATION_AND_NAVIGATION_NAVIGATION_VALUE);
            return FALSE;
        }
        // Just return FALSE if we are waiting for confirmation
        if (location_and_navigation_indication_sent != 0)
        {
            ble_trace1("wait confirmation handle:%02x", HDLC_LOCATION_AND_NAVIGATION_NAVIGATION_VALUE);
            return FALSE;
        }
        // Read the value of the characteristic
        bleprofile_ReadHandle(HDLC_LOCATION_AND_NAVIGATION_NAVIGATION_VALUE, &db_pdu);
        // Notify property is true. If client has registered for notification
        if (p_bonded->location_and_navigation_navigation_client_configuration & CCC_NOTIFICATION)
        {
            ble_trace2("notify len:%d handle:%02x", db_pdu.len, HDLC_LOCATION_AND_NAVIGATION_NAVIGATION_VALUE);
            bleprofile_sendNotification(HDLC_LOCATION_AND_NAVIGATION_NAVIGATION_VALUE, (UINT8 *)db_pdu.pdu, db_pdu.len);
        }
    }
    return TRUE;
}

