/*
 * This file has been automatically generated by the WICED Smart Designer.
 * BLE device's GATT database, device configuration, function that can be used
 * to send notifications and indications.
 *
 */

// ibeacon_managed_db.c

#include "bleprofile.h"
#include "bleapp.h"
#include "gpiodriver.h"
#include "string.h"
#include "stdio.h"
#include "platform.h"
#include "ibeacon_managed_db.h"

const UINT8 gatt_database[]= // Define GATT database
{
// ***** Primary service 'Generic Access'
    //<Name>Generic Access</Name>
    //<Uuid>1800</Uuid>
    //Service handle: HDLS_GENERIC_ACCESS
    //Service UUID: UUID_SERVICE_GAP
    PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ACCESS, UUID_SERVICE_GAP),

    //<Name>Device Name</Name>
    //<Uuid>2A00</Uuid>
    CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_DEVICE_NAME,
                           HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE,
                           UUID_CHARACTERISTIC_DEVICE_NAME,
                           LEGATTDB_CHAR_PROP_READ,
                           LEGATTDB_PERM_READABLE,
                           15),
    'i','b','e','a','c','o','n','_','m','a','n','a','g','e','d',

    //<Name>Appearance</Name>
    //<Uuid>2A01</Uuid>
    CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_APPEARANCE,
                           HDLC_GENERIC_ACCESS_APPEARANCE_VALUE,
                           UUID_CHARACTERISTIC_APPEARANCE,
                           LEGATTDB_CHAR_PROP_READ,
                           LEGATTDB_PERM_READABLE,
                           2),
    BIT16_TO_8(APPEARANCE_GENERIC_TAG),

// ***** Primary service 'Generic Attribute'
    //<Name>Generic Attribute</Name>
    //<Uuid>1801</Uuid>
    //Service handle: HDLS_GENERIC_ATTRIBUTE
    //Service UUID: UUID_SERVICE_GATT
    PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ATTRIBUTE, UUID_SERVICE_GATT),

// ***** Primary service 'ibeacon_managed'
    //<Name>ibeacon_managed</Name>
    //<Uuid>b1 a8 2c 30 cf f8 41 03 ab 07 61 c8 7d d3 f3 72</Uuid>
    //Service handle: HDLS_IBEACON_MANAGED
    //Service UUID: __UUID_IBEACON_MANAGED
    PRIMARY_SERVICE_UUID128 (HDLS_IBEACON_MANAGED, __UUID_IBEACON_MANAGED),

    //<Name>company_uuid</Name>
    //<Uuid>c3 70 01 a8 63 4b 44 7d 8e 6b 0c a0 38 e1 cb ab</Uuid>
    CHARACTERISTIC_UUID128_WRITABLE (HDLC_IBEACON_MANAGED_COMPANY_UUID,
                           HDLC_IBEACON_MANAGED_COMPANY_UUID_VALUE,
                           __UUID_IBEACON_MANAGED_COMPANY_UUID,
                           LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE,
                           LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ,
                           16),
    0x87,0xf8,0xac,0xb5,0x9a,0xd0,0x29,0xa7,0x20,0x4c,0xf0,0x80,0xe2,0xb5,0x5c,0x0e,

    //<Name>major_id</Name>
    //<Uuid>6e 0c 91 ac 8f 5d 43 c3 8e 00 4d 54 dc a2 b8 26</Uuid>
    CHARACTERISTIC_UUID128_WRITABLE (HDLC_IBEACON_MANAGED_MAJOR_ID,
                           HDLC_IBEACON_MANAGED_MAJOR_ID_VALUE,
                           __UUID_IBEACON_MANAGED_MAJOR_ID,
                           LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE,
                           LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ,
                           2),
    BIT16_TO_8(0x12),

    //<Name>minor_id</Name>
    //<Uuid>a8 f6 71 d3 2e 30 49 4e a7 69 76 2a 72 a1 ce 0a</Uuid>
    CHARACTERISTIC_UUID128_WRITABLE (HDLC_IBEACON_MANAGED_MINOR_ID,
                           HDLC_IBEACON_MANAGED_MINOR_ID_VALUE,
                           __UUID_IBEACON_MANAGED_MINOR_ID,
                           LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE,
                           LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ,
                           2),
    BIT16_TO_8(0x01),

    //<Name>measured_power</Name>
    //<Uuid>cd da 8f 65 f0 62 4b 02 bc ec 16 e0 9f 92 05 e2</Uuid>
    CHARACTERISTIC_UUID128_WRITABLE (HDLC_IBEACON_MANAGED_MEASURED_POWER,
                           HDLC_IBEACON_MANAGED_MEASURED_POWER_VALUE,
                           __UUID_IBEACON_MANAGED_MEASURED_POWER,
                           LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE,
                           LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ,
                           1),
    0xca,

};
// Length of the GATT database
const UINT16 gatt_database_len = sizeof(gatt_database);

// Following structure defines GPIO configuration used by the application
const BLE_PROFILE_GPIO_CFG ibeacon_managed_gpio_cfg =
{
    {
        GPIO_PIN_WP,                               // This need to be used to enable/disable NVRAM write protect
        GPIO_PIN_BUTTON, -1, -1, -1, 
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 // Other GPIOs are not used
    },
    /*.gpio_flag =*/
    {
        GPIO_SETTINGS_WP,
        GPIO_SETTINGS_BUTTON | GPIO_BOTHEDGE_INT, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    }
};

// Main vendor specific service
UINT8 ibeacon_managed_uuid_main_vsc_service[16] = {__UUID_IBEACON_MANAGED};
// Registers timer. Should be called from ibeacon_managed_create()
void ibeacon_managed_reg_timer()
{
}

// Updates __HOSTINFO by the value written by peer.
// Returns true if any persistent value is changed
BOOL __write_handler(UINT16 handle, int len, UINT8 *attrPtr)
{
    BOOL res = FALSE;
    if (handle == HDLC_IBEACON_MANAGED_COMPANY_UUID_VALUE)
    {
        if (len != 16)
        {
            ble_trace2("bad length:%d handle:%04x", len, handle);
        }
        else
        {
            //call custom on_write function
            ble_trace1("write handle:%04x", handle);
            res = on_write_ibeacon_managed_company_uuid(len, attrPtr);
        }
    }
    if (handle == HDLC_IBEACON_MANAGED_MAJOR_ID_VALUE)
    {
        if (len != 2)
        {
            ble_trace2("bad length:%d handle:%04x", len, handle);
        }
        else
        {
            //call custom on_write function
            ble_trace1("write handle:%04x", handle);
            res = on_write_ibeacon_managed_major_id(len, attrPtr);
        }
    }
    if (handle == HDLC_IBEACON_MANAGED_MINOR_ID_VALUE)
    {
        if (len != 2)
        {
            ble_trace2("bad length:%d handle:%04x", len, handle);
        }
        else
        {
            //call custom on_write function
            ble_trace1("write handle:%04x", handle);
            res = on_write_ibeacon_managed_minor_id(len, attrPtr);
        }
    }
    if (handle == HDLC_IBEACON_MANAGED_MEASURED_POWER_VALUE)
    {
        if (len != 1)
        {
            ble_trace2("bad length:%d handle:%04x", len, handle);
        }
        else
        {
            //call custom on_write function
            ble_trace1("write handle:%04x", handle);
            res = on_write_ibeacon_managed_measured_power(len, attrPtr);
        }
    }
    return res;
}

// It should be called when 'Device Name' is changed.
BOOL store_in_db_generic_access_device_name(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'Appearance' is changed.
BOOL store_in_db_generic_access_appearance(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_GENERIC_ACCESS_APPEARANCE_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_GENERIC_ACCESS_APPEARANCE_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'company_uuid' is changed.
BOOL store_in_db_ibeacon_managed_company_uuid(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_IBEACON_MANAGED_COMPANY_UUID_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_IBEACON_MANAGED_COMPANY_UUID_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'major_id' is changed.
BOOL store_in_db_ibeacon_managed_major_id(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_IBEACON_MANAGED_MAJOR_ID_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_IBEACON_MANAGED_MAJOR_ID_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'minor_id' is changed.
BOOL store_in_db_ibeacon_managed_minor_id(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_IBEACON_MANAGED_MINOR_ID_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_IBEACON_MANAGED_MINOR_ID_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'measured_power' is changed.
BOOL store_in_db_ibeacon_managed_measured_power(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x", value_len, HDLC_IBEACON_MANAGED_MEASURED_POWER_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_IBEACON_MANAGED_MEASURED_POWER_VALUE, &db_pdu);
    return TRUE;
}

